ssl:
  key: "/certificates/firo.key"
  certificate: "/certificates/firo.crt"
  root: "/certificates/RootCA.pem"
mounts:
  - name: "static"
    type: "SPA"
    path: "/"
    directory: "../dist"
origins:
  - "http://localhost"
  - "https://localhost"
  - "http://localhost:80"
  - "https://localhost:443"