name: Deploy

on:
  push:
    branches: 
      - main
      - release
    tags:
      - 'v*.*.*'

env:
  PLATFORM: linux/amd64, linux/arm64
  REGISTRY: ghcr.io
  IMAGE_CHANNEL: ${{ github.ref_type == 'tag' && github.ref || (github.ref == 'refs/heads/release' && 'stable' || 'nightly') }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  deploy:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Dependencies
        run: pnpm ci
      
      - name: Build
        run: pnpm run build
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_CHANNEL }}
          platforms: ${{ env.PLATFORM }}
          cache-from: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_CHANNEL }}
          build-args: BUILDKIT_INLINE_CACHE=1
