name: CI

on:
  push:
    branches: 
      - "main"
      - "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux/amd64, linux/arm64
      MAIN_IMAGE: ghcr.io/${{ github.repository_owner }}/robot-web-interface:${{ github.ref == 'refs/heads/main' && 'stable' || 'nightly' }}

    steps:
      # github.repository_owner can contain uppercase chars, 
      # but docker repository address must be all lowercase
      - name: Lowercase image name
        run: |
          echo "MAIN_IMAGE=${MAIN_IMAGE,,}" >>${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Dependecies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.MAIN_IMAGE }}
          platforms: ${{ env.PLATFORM }}
          cache-from: ${{ env.MAIN_IMAGE }}
          build-args: BUILDKIT_INLINE_CACHE=1
